# voidlinux remote repositories (x86_64/glibc)
repository=https://cephalopo.net/mirror/voidlinux/current/multilib/bootstrap
repository=https://cephalopo.net/mirror/voidlinux/current/multilib
repository=https://cephalopo.net/mirror/voidlinux/current/multilib/nonfree
