# voidlinux remote repositories (musl)
repository=https://cephalopo.net/mirror/voidlinux/current/musl/bootstrap
repository=https://cephalopo.net/mirror/voidlinux/current/musl
repository=https://cephalopo.net/mirror/voidlinux/current/musl/nonfree
repository=https://cephalopo.net/mirror/voidlinux/current/musl/debug
